name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      subdomains:
        description: 'JSON list of subdomains (e.g. ["basket", "order-management"])'
        type: string
      env:
        description: 'Target environment'
        type: choice
        default: sandbox
        options:
          - sandbox
          - dev
          - qa
          - performance
          - staging
          - staging-green
          - production
        required: true

permissions:
  actions: write
  id-token: write
  contents: read

jobs:
  generate-matrix:
    uses: ./.github/workflows/reusable-workflow.yaml