name: Called Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target environment'
        type: choice
        default: sandbox
        options:
          - sandbox
          - dev
          - qa
          - performance
          - staging
          - staging-green
          - production
        required: true
      subdomains:
        description: 'JSON list of subdomains (e.g. ["basket", "order-management"])'
        type: string
      deploy_common:
        description: 'Common Resources Deployment'
        required: false
        type: boolean
        default: false

permissions:
  actions: write
  id-token: write
  contents: read

jobs:
  deploy_infra:
    uses: Shake-Shack-Engineering/shared-workflows/.github/workflows/infrastructure-deploy.yaml@poc
    with:
      env: ${{ github.event.inputs.env }}
      subdomains: ${{ github.event.inputs.subdomains }}
      deploy_common: ${{ github.event.inputs.deploy_common }}
    secrets:
      ORG_REPO_READ_PRIVATE_KEY: ${{ secrets.ORG_REPO_READ_PRIVATE_KEY }}
      ORG_REPO_READ_APP_ID: ${{ secrets.ORG_REPO_READ_APP_ID }}
