name: CI - Scan Terraform Files

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  discover_changed_tf_folders:
    name: Discover changed Terraform folders
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      has_changes: ${{ steps.set-matrix.outputs.has_changes }}
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute changed folders and build matrix JSON (top-level only)
        id: set-matrix
        shell: bash
        run: |
          set -euo pipefail

          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          # Find changed Terraform files
          mapfile -t files < <(git diff --name-only "$BASE_SHA" "$HEAD_SHA" -- '**/*.tf' '**/*.tfvars' | sed 's#^./##')

          if [ ${#files[@]} -eq 0 ]; then
            echo "No Terraform changes detected."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo 'matrix=[]' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Get unique directories for changed files
          dirs=$(printf '%s\n' "${files[@]}" | xargs -n1 dirname | sort -u)

          echo "Changed dirs (raw):"
          printf '%s\n' "$dirs"

          # Map each dir to its TOP-LEVEL parent:
          # - "fake-folder/dev"  -> "fake-folder"
          # - "delivery"         -> "delivery"
          # - "." (repo root)    -> "."
          toplevel=$(while IFS= read -r d; do
            [ -z "$d" ] && continue
            if [ "$d" = "." ]; then
              echo "."
            else
              echo "${d%%/*}"
            fi
          done <<< "$dirs" | sort -u)

          echo "Top-level dirs:"
          printf '%s\n' "$toplevel"

          # Build matrix as: [{"dir":"folder1"},{"dir":"folder2"}]
          if [ -z "$toplevel" ]; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo 'matrix=[]' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          json_matrix=$(printf '%s\n' "$toplevel" | jq -R '{dir: .}' | jq -s -c '.')
          echo "Generated matrix: $json_matrix"

          echo "has_changes=true" >> "$GITHUB_OUTPUT"
          printf 'matrix=%s\n' "$json_matrix" >> "$GITHUB_OUTPUT"

  terraform_scan:
    name: Terraform CI • ${{ matrix.dir }}
    needs: discover_changed_tf_folders
    if: needs.discover_changed_tf_folders.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.discover_changed_tf_folders.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to Terraform directory
        run: |
          pwd 
          ls -ltra
          if [ "${{ matrix.dir }}" != "." ]; then
            cd "${{ matrix.dir }}"
            ls -ltra
            git branch
          fi
        shell: bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint (with plugin cache)
        uses: terraform-linters/setup-tflint@v4 
  